# Generated by Django 5.1 on 2024-09-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeevariety',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
